# A linha "version" foi removida, corrigindo o warning.

networks:
  vibracore-net:
    driver: bridge

services:
  zookeeper:
    # Imagem substituída pela oficial da Confluent
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks:
      - vibracore-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # Imagem substituída pela oficial da Confluent
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks:
      - vibracore-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  product-service:
    build:
      context: .
      dockerfile: ./services/product_service/Dockerfile
    container_name: vibracore_product_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/product_service:/app/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - kafka
    networks:
      - vibracore-net

  review-service:
    build:
      context: .
      dockerfile: ./services/review_service/Dockerfile
    container_name: vibracore_review_service
    depends_on:
      - kafka
    networks:
      - vibracore-net