version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibracore_product_service
    ports:
      - "8000:8000"
    volumes:
      # Mapeia o código local para a pasta /app/src, onde o código vive agora
      - ./services/product_service:/app/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload