[project]
name = "vibracore"
version = "0.1.0"
description = "Pequeno projeto, fim de semana."
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "black",
    "pre-commit",
]
